meta_product_name: "Chomp"
meta_title: "Chomp - Dunno where to eat? Let us decide!"
meta_description: "Don't know where to eat as a group? Everyone is too indecisive? Let Chomp decide for you. "
meta_image: "cover.png" # should exist in `app/assets/images/`
